name: pantrikita
description: "PantriKita Flutter Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  get: ^4.6.6
  fluttertoast:
  http:
  intl:
  flutter_bloc:
  flutter_svg: ^2.0.16
  page_transition:
  shared_preferences: ^2.2.3
  google_nav_bar: ^5.0.6
  get_storage: ^2.0.3
  carousel_slider: ^5.0.0
  internet_connection_checker:
  get_it:
  dartz:
  cached_network_image: ^3.3.1
  equatable:
  stream_transform:
  url_launcher: ^6.3.0
  awesome_notifications:
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  easy_debounce: ^2.0.3
  loading_animation_widget: ^1.2.1
  lottie: ^3.1.2
  fluid_dialog: ^2.0.0
  top_snackbar_flutter: ^3.1.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/image/
    - .env