// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-G_NSkxmAOe7ZQhW7bwBDdUsZ9bLscJY',
    appId: '1:377082337159:web:b452953249aa74e0702522',
    messagingSenderId: '377082337159',
    projectId: 'pantrikita-app',
    authDomain: 'pantrikita-app.firebaseapp.com',
    storageBucket: 'pantrikita-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjQWyQb2VeJy_n7pDaxVe2G3lXCZWMBwE',
    appId: '1:377082337159:android:589c40c96c52eda3702522',
    messagingSenderId: '377082337159',
    projectId: 'pantrikita-app',
    storageBucket: 'pantrikita-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCISjmeEIv9m_Dr8TYse672mmNkiDDoAO0',
    appId: '1:377082337159:ios:91f55f6ee6190588702522',
    messagingSenderId: '377082337159',
    projectId: 'pantrikita-app',
    storageBucket: 'pantrikita-app.firebasestorage.app',
    iosBundleId: 'com.example.pantrikita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCISjmeEIv9m_Dr8TYse672mmNkiDDoAO0',
    appId: '1:377082337159:ios:91f55f6ee6190588702522',
    messagingSenderId: '377082337159',
    projectId: 'pantrikita-app',
    storageBucket: 'pantrikita-app.firebasestorage.app',
    iosBundleId: 'com.example.pantrikita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-G_NSkxmAOe7ZQhW7bwBDdUsZ9bLscJY',
    appId: '1:377082337159:web:285c730370b02672702522',
    messagingSenderId: '377082337159',
    projectId: 'pantrikita-app',
    authDomain: 'pantrikita-app.firebaseapp.com',
    storageBucket: 'pantrikita-app.firebasestorage.app',
  );
}
